CREATE DATABASE PROJETO_JNMOURA; /*CRIE BASE DE DADOS*/

USE PROJETO_JNMOURA; /*USE A BASE DE DADOS*/

CREATE TABLE IF NOT EXISTS CONTATOS
(
	ID 			 	INT 			NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    NOME		  	VARCHAR(255) 	NOT NULL 						    ,
    TELEFONE 	  	VARCHAR(15) 	NOT NULL 						 	,
    ENDERECO	    VARCHAR(255) 	NOT NULL						 	,
    DATA_CADASTRO   DATE 			NOT NULL
);
